# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node.js
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CI: false
      REACT_APP_NETWORK_URL: https://mainnet.infura.io/v3/f067a90d45464690bb0a8d7ca6ae1101
      REACT_APP_UNISWAP_THE_GRAPH: https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: borales/actions-yarn@v4
      with:
        cmd: install
    - run: cp .env.example .env
    - run: echo "REACT_APP_NETWORK_URL = $REACT_APP_NETWORK_URL" >> .env
    - run: echo "REACT_APP_UNISWAP_THE_GRAPH = $REACT_APP_UNISWAP_THE_GRAPH" >> .env
    - run: npm run build --if-present
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build


